"""Shared fixtures: simulated devices and synthetic captures.

All test vectors are generated by ppk2lab's own signal builders and
simulator; nothing is copied from other projects.
"""

from __future__ import annotations

import pytest

from ppk2lab.capture.model import Capture
from ppk2lab.device import PPK2
from ppk2lab.testing.profiles import ArrayProfile, ConstantProfile, Profile
from ppk2lab.transport.mock import MockTransport, SimulatedPPK2


def open_simulated(
    profile: Profile | None = None,
    *,
    gaps: dict[int, int] | None = None,
    **kwargs,
) -> PPK2:
    simulator = SimulatedPPK2(
        profile=profile if profile is not None else ConstantProfile(100.0),
        gaps=gaps,
        **kwargs,
    )
    return PPK2.open(transport=MockTransport(simulator), simulate=True)


def capture_of(
    profile: Profile | None = None,
    *,
    samples: int = 2000,
    gaps: dict[int, int] | None = None,
) -> Capture:
    device = open_simulated(profile, gaps=gaps)
    try:
        result = device.capture(sample_limit=samples)
    finally:
        device.close()
    assert result.capture is not None
    return result.capture


def wave_capture(
    logic: bytes | list[int],
    *,
    current_ua: float = 100.0,
    gaps: dict[int, int] | None = None,
    tail_samples: int = 50,
) -> Capture:
    """A capture whose logic follows the given per-sample byte sequence."""
    if not isinstance(logic, bytes | bytearray):
        logic = bytes(logic)
    profile = ArrayProfile(current_ua, logic, default_logic=logic[-1] if logic else 0)
    return capture_of(profile, samples=len(logic) + tail_samples, gaps=gaps)


@pytest.fixture
def sim_device():
    device = open_simulated()
    yield device
    device.close()


@pytest.fixture(autouse=True)
def _no_ambient_simulate(monkeypatch):
    """Never let a developer's exported `PPK2LAB_SIMULATE` reach the code.

    `PPK2.open` and `discover` both consult it whenever `simulate` is left at
    its default, so with the variable exported a test that expects a real
    device lookup to fail instead finds a simulator, and one that asserts a
    handle is *not* labelled simulated sees it labelled. Tests that want the
    variable set it themselves with `monkeypatch.setenv`, which runs after
    this fixture.
    """
    monkeypatch.delenv("PPK2LAB_SIMULATE", raising=False)
