"""Live decimation: the port of the console's decimator, and the grid it draws.

Two kinds of test live here, and the difference matters.

The vector test replays `tests/vectors/decimation-golden.json` and compares. It
is a regression guard, not an independent check -- the vector was generated by
this same code, so on its own it only proves the implementation has not
changed. What makes it worth having is the other side: `webui/tests/decimation
.test.ts` drives the same input through the TypeScript `Decimator`, so the
vector is a contract two languages have to satisfy, and a drift in either one
shows up as a failure in the other.

Everything below it is independent: invariants and boundary values worked out
from the definitions rather than read back from the implementation.
"""

from __future__ import annotations

import json
import math
import pathlib

import pytest

from ppk2lab.capture.stats import IMPLAUSIBLE_CURRENT_UA, QUANTILE_MIN_UA
from ppk2lab_web.buckets import (
    HIST_BINS,
    HIST_PER_DECADE,
    SAMPLES_PER_BUCKET,
    Tier0Accumulator,
    hist_add,
    hist_bin_value,
    new_histogram,
)

VECTOR = pathlib.Path(__file__).parent / "vectors" / "decimation-golden.json"


def _replay(events: list[dict]) -> tuple[Tier0Accumulator, list]:
    acc = Tier0Accumulator()
    buckets = []
    for event in events:
        if event["kind"] == "gap":
            buckets.extend(acc.add_gap(event["missing"]))
        else:
            buckets.extend(
                acc.add_samples(event["ua"], bytes(event["range"]), bytes(event["logic"]))
            )
    return acc, buckets


# ---------------------------------------------------------------------------
# The cross-language vector


def test_the_golden_vector_still_describes_this_implementation():
    vector = json.loads(VECTOR.read_text())
    acc, buckets = _replay(vector["events"])

    assert len(buckets) == len(vector["buckets"])
    for got, want in zip(buckets, vector["buckets"], strict=True):
        assert got.start_index == want["start_index"]
        assert got.t0 == want["t0"]
        assert got.min_ua == want["min"]
        assert got.max_ua == want["max"]
        assert got.sum_ua == want["sum"]
        assert (got.n, got.gap, got.excluded) == (want["n"], want["gap"], want["excluded"])
        assert got.range_mask == want["rangeMask"]
        assert (got.logic_any, got.logic_all) == (want["logicAny"], want["logicAll"])
        assert got.edges == want["edges"]

    counters = vector["counters"]
    assert acc.total_stored == counters["total_stored"]
    assert acc.total_missing == counters["total_missing"]
    assert acc.total_excluded == counters["total_excluded"]
    assert acc.gap_count == counters["gap_count"]

    nonzero = {str(i): v for i, v in enumerate(acc.histogram) if v}
    assert nonzero == vector["histogram_nonzero"]


def test_the_vector_covers_more_than_one_range_and_one_decade():
    """A vector that sits in one current and one range would pass while proving
    almost nothing about either implementation."""
    vector = json.loads(VECTOR.read_text())
    masks = {b["rangeMask"] for b in vector["buckets"]}
    assert len(masks) >= 3, masks
    assert len(vector["histogram_nonzero"]) >= 3
    assert any(b["gap"] for b in vector["buckets"])
    assert any(b["edges"] for b in vector["buckets"])


# ---------------------------------------------------------------------------
# Independent invariants


def test_every_closed_bucket_accounts_for_all_hundred_samples():
    """`n + gap + excluded` is the whole bucket.

    The three bins are the three things that can be true of a sample slot: it
    arrived and is usable, it never arrived, or it arrived and cannot be
    trusted. A slot that fell out of all three would be loss the console never
    shows.
    """
    vector = json.loads(VECTOR.read_text())
    _acc, buckets = _replay(vector["events"])
    for bucket in buckets:
        assert bucket.n + bucket.gap + bucket.excluded == SAMPLES_PER_BUCKET


def test_counters_agree_with_the_buckets_they_summarise():
    vector = json.loads(VECTOR.read_text())
    acc, buckets = _replay(vector["events"])
    # The last bucket is still open, so the counters lead the closed buckets.
    assert sum(b.n for b in buckets) <= acc.total_stored
    assert sum(b.gap for b in buckets) <= acc.total_missing
    # A gap spanning three buckets is one gap, not three.
    assert acc.gap_count == 2
    assert acc.covered_fraction() == acc.total_stored / (acc.total_stored + acc.total_missing)


@pytest.mark.parametrize("seam", [1, 37, 99, 100, 101, 150, 199])
def test_an_edge_is_counted_across_a_block_seam(seam):
    """Blocks are an artefact of USB delivery, not of the signal.

    A `SampleBlock` is a gap-free run and the parser emits many per second, so
    resetting the edge state at a block boundary would drop one transition per
    block -- tens per second, each invisible on its own and all of them wrong.
    """
    logic = bytes((i // 3) % 2 * 0xFF for i in range(200))
    ua = [10.0] * 200
    ranges = bytes(200)

    whole = Tier0Accumulator()
    whole_buckets = whole.add_samples(ua, ranges, logic) + whole.flush()

    split = Tier0Accumulator()
    split_buckets = split.add_samples(ua[:seam], ranges[:seam], logic[:seam])
    split_buckets += split.add_samples(ua[seam:], ranges[seam:], logic[seam:])
    split_buckets += split.flush()

    assert sum(b.edges for b in split_buckets) == sum(b.edges for b in whole_buckets)


def test_a_gap_breaks_edge_continuity():
    """The line was not observed across the hole, so the sample after it starts
    no transition -- counting one would invent an edge nobody saw."""
    acc = Tier0Accumulator()
    acc.add_samples([1.0], bytes([0]), bytes([0x00]))
    acc.add_gap(10)
    acc.add_samples([1.0], bytes([0]), bytes([0xFF]))
    (bucket,) = acc.flush()
    assert bucket.edges == 0


def test_a_gap_spreads_across_buckets_and_counts_once():
    acc = Tier0Accumulator()
    closed = acc.add_gap(250)
    assert [b.gap for b in closed] == [100, 100]
    assert acc.gap_count == 1
    assert acc.total_missing == 250
    # The third bucket is still open with the remaining 50.
    (partial,) = acc.flush()
    assert partial.gap == 50


def test_a_gap_of_unknown_size_advances_nothing():
    """A gap the parser could not size cannot be placed on the timeline: filling
    a guess would move every later sample. The session is marked degraded
    instead, so the console can say the timeline is no longer trustworthy."""
    acc = Tier0Accumulator()
    assert acc.add_gap(None) == []
    assert acc.timeline_degraded
    assert acc.total_missing == 0
    assert acc.gap_count == 0


def test_an_empty_bucket_claims_nothing():
    """min/max are meaningless with no samples, and 0xff would claim every
    channel was high."""
    acc = Tier0Accumulator()
    (bucket,) = acc.add_gap(100)
    assert (bucket.min_ua, bucket.max_ua) == (0.0, 0.0)
    assert bucket.logic_all == 0
    assert bucket.n == 0


def test_a_flushed_bucket_leaves_the_timeline_where_it_really_ended():
    """A short bucket must not advance the index by a full width, or every
    later timestamp is wrong by the difference."""
    acc = Tier0Accumulator()
    acc.add_samples([1.0] * 30, bytes(30), bytes(30))
    (short,) = acc.flush()
    assert short.start_index == 0
    assert short.n == 30
    acc.add_samples([1.0] * 100, bytes(100), bytes(100))
    nxt = acc.flush()
    assert not nxt  # exactly one bucket closed on its own
    acc2 = Tier0Accumulator()
    acc2.add_samples([1.0] * 30, bytes(30), bytes(30))
    acc2.flush()
    closed = acc2.add_samples([1.0] * 100, bytes(100), bytes(100))
    assert closed[0].start_index == 30


# ---------------------------------------------------------------------------
# Samples that arrived and cannot be used


def test_an_unusable_sample_is_neither_stored_nor_missing():
    """It was delivered, so calling it a gap accuses the instrument of loss it
    did not commit; it is not usable, so putting it in `n` poisons the mean."""
    acc = Tier0Accumulator()
    ua = [10.0, math.nan, 20.0, IMPLAUSIBLE_CURRENT_UA * 2, 30.0]
    ranges = bytes([0, 0, 0, 0, 7])  # the last one is an invalid range field
    logic = bytes(5)
    acc.add_samples(ua, ranges, logic)
    (bucket,) = acc.flush()

    assert bucket.n == 2  # 10.0 and 20.0
    assert bucket.excluded == 3
    assert bucket.gap == 0
    assert bucket.sum_ua == 30.0
    assert bucket.min_ua == 10.0
    assert bucket.max_ua == 20.0
    assert acc.total_excluded == 3
    assert acc.total_stored == 2


def test_an_unusable_sample_still_reports_its_range_and_its_logic():
    """The range field and the logic byte were real. Dropping them would hide
    framing damage and throw away digital data that is valid whether or not the
    current could be converted."""
    acc = Tier0Accumulator()
    acc.add_samples([math.nan], bytes([7]), bytes([0b1010_0000]))
    (bucket,) = acc.flush()
    assert bucket.range_mask == 1 << 7
    assert bucket.logic_any == 0b1010_0000


def test_an_unusable_sample_stays_out_of_the_distribution():
    """Bin 0 means 'at or below the 200 nA floor', which the console prints as
    an upper bound on a real current. Letting an unconvertible sample inflate
    it would turn a calibration failure into a claim about the DUT."""
    acc = Tier0Accumulator()
    acc.add_samples([math.nan, math.nan], bytes(2), bytes(2))
    assert sum(acc.histogram) == 0


# ---------------------------------------------------------------------------
# The distribution grid


def test_the_grid_places_its_boundary_values_where_the_console_does():
    hist = new_histogram()
    cases = {
        QUANTILE_MIN_UA: 0,
        math.nextafter(QUANTILE_MIN_UA, math.inf): 1,
        2.0: 1 + math.floor(math.log10(2.0 / QUANTILE_MIN_UA) * HIST_PER_DECADE),
        0.0: 0,
        -1.0: 0,
        1e9: HIST_BINS,
    }
    for value, expected_bin in cases.items():
        before = hist[expected_bin]
        hist_add(hist, value)
        assert hist[expected_bin] == before + 1, value


def test_nan_lands_in_the_underflow_bin():
    """`not (ua > FLOOR)` is NaN-true in both languages; `ua <= FLOOR` is not.
    Spelled the other way the two grids would disagree on the value a device
    with missing calibration constants produces most."""
    hist = new_histogram()
    hist_add(hist, math.nan)
    assert hist[0] == 1


def test_the_top_bin_is_also_the_overflow_bin():
    hist = new_histogram()
    hist_add(hist, 1e6)
    hist_add(hist, 1e12)
    assert hist[HIST_BINS] >= 1
    assert len(hist) == HIST_BINS + 1


def test_a_bin_reports_its_geometric_midpoint():
    assert hist_bin_value(0) == QUANTILE_MIN_UA
    lower = hist_bin_value(1)
    upper = hist_bin_value(1 + HIST_PER_DECADE)
    assert upper / lower == pytest.approx(10.0)
