"""Self-produced test signal generation.

All ppk2lab golden vectors are generated by this package (or by the project's
own hardware fixtures); no fixture data is copied from other projects. The
builders are public so downstream users can generate their own test captures.
"""

from .profiles import (
    ArrayProfile,
    ConstantProfile,
    DemoActivityProfile,
    Profile,
    StepProfile,
)
from .signals import merge_logic, spi_wave, uart_frame_bits, uart_wave

__all__ = [
    "ArrayProfile",
    "ConstantProfile",
    "DemoActivityProfile",
    "Profile",
    "StepProfile",
    "merge_logic",
    "spi_wave",
    "uart_frame_bits",
    "uart_wave",
]
