"""Generate the cross-language decimation vector.

    python tests/vectors/generate_decimation_golden.py

The console decimates in TypeScript and the server decimates in Python, and the
two have to produce the same buckets from the same samples or a live trace
disagrees with itself. Nothing else in either test suite can catch that: each
side is internally consistent no matter what the other does.

So the vector is the contract. It carries the *input* -- explicit
(microamps, range, logic) triples and gap lengths, so neither side has to
re-derive a profile -- and the buckets Python produces from it.
`tests/test_web_buckets.py` checks the Python side against it and against
invariants the vector cannot make circular; `webui/tests/decimation.test.ts`
drives the same input through `Decimator` and compares.

Generation method, per CLAUDE.md's rule that a vector records how it was made:
every sample comes from `ppk2lab.testing.profiles.DemoActivityProfile`, the
profile `--simulate` ships, read at the indices `SCRIPT` names. Ranges come
from the simulator's own `current_to_range_adc`, so they are the ranges a PPK2
would report for those currents. Nothing is random and nothing is
hand-written.

The run is deliberately awkward:

* the samples are split into blocks that do not align to the 100-sample bucket
  boundary, so an edge is counted across a block seam -- the case a per-block
  reset gets wrong once per block, invisibly;
* one gap spans more than a bucket, so the spread-across-buckets loop runs;
* one gap is shorter than the space left in the current bucket;
* the run ends mid-bucket, so the last bucket is still open and is not emitted;
* the sample runs walk three regions of the demo cycle, so the vector spans
  three current decades and two measurement ranges rather than sitting in one.

Re-run it after any deliberate change to either implementation, and read the
diff: a change to the vector is a change to a contract two languages share.
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "src"))

from ppk2lab.testing.profiles import DemoActivityProfile
from ppk2lab.transport.mock import current_to_range_adc
from ppk2lab_web.buckets import Tier0Accumulator

OUT = pathlib.Path(__file__).with_name("decimation-golden.json")

#: The run, in order: ``(kind, count, profile_index)``.
#:
#: Block lengths deliberately do not align to the 100-sample bucket boundary,
#: and the profile indices walk the three regions of the demo cycle so the
#: vector covers more than one current decade and more than one range:
#: 0-1499 is the 12 mA burst with D1 high and an SPI transaction on D3-D6,
#: 1500-2340 is a 9600-baud UART frame on D0 at 25 uA, and the remainder is
#: the 6 uA sleep. D2 carries a 1 kHz square wave throughout.
SCRIPT: list[tuple[str, int, int]] = [
    ("samples", 137, 1_400),  # burst, ending mid-bucket
    ("samples", 213, 1_537),  # seam at 137: an edge must be counted across it
    ("gap", 250, 0),  # spans two full buckets and part of a third
    ("samples", 300, 1_750),  # UART traffic on D0
    ("gap", 30, 0),  # fits inside the bucket being filled
    ("samples", 170, 2_330),  # crosses UART -> sleep, so the range changes
    ("samples", 60, 5_000),  # sleep; leaves the last bucket open
]


def build() -> dict:
    profile = DemoActivityProfile()
    events: list[dict] = []
    acc = Tier0Accumulator()
    buckets: list[dict] = []

    for kind, count, start in SCRIPT:
        if kind == "gap":
            for bucket in acc.add_gap(count):
                buckets.append(_bucket_json(bucket))
            events.append({"kind": "gap", "missing": count})
            continue
        ua_list: list[float] = []
        range_list: list[int] = []
        logic_list: list[int] = []
        for offset in range(count):
            current_ua, logic = profile.sample(start + offset)
            range_index, _adc = current_to_range_adc(current_ua)
            ua_list.append(current_ua)
            range_list.append(range_index)
            logic_list.append(logic)
        for bucket in acc.add_samples(ua_list, bytes(range_list), bytes(logic_list)):
            buckets.append(_bucket_json(bucket))
        events.append({"kind": "samples", "ua": ua_list, "range": range_list, "logic": logic_list})

    return {
        "_comment": "Generated by tests/vectors/generate_decimation_golden.py. Do not hand-edit.",
        "samples_per_bucket": 100,
        "events": events,
        "buckets": buckets,
        "counters": {
            "total_stored": acc.total_stored,
            "total_missing": acc.total_missing,
            "total_excluded": acc.total_excluded,
            "gap_count": acc.gap_count,
        },
        # Only the non-zero bins: 169 mostly-zero entries would bury the signal
        # in a diff, and a bin that should be zero is caught by the total.
        "histogram_nonzero": {str(i): value for i, value in enumerate(acc.histogram) if value},
    }


def _bucket_json(bucket) -> dict:
    return {
        "start_index": bucket.start_index,
        "t0": bucket.t0,
        "min": bucket.min_ua,
        "max": bucket.max_ua,
        "sum": bucket.sum_ua,
        "n": bucket.n,
        "gap": bucket.gap,
        "excluded": bucket.excluded,
        "rangeMask": bucket.range_mask,
        "logicAny": bucket.logic_any,
        "logicAll": bucket.logic_all,
        "edges": bucket.edges,
    }


if __name__ == "__main__":
    OUT.write_text(json.dumps(build(), indent=2) + "\n")
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}")
